---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: V-38669 - The postfix service must be enabled for mail delivery (install postfix)
  apt:
    name: postfix
    state: latest
  tags:
    - mail
    - cat3
    - V-38669

- name: V-38669 - The postfix service must be enabled for mail delivery (ebable postfix)
  service:
    name: postfix
    state: started
    enabled: yes
  tags:
    - mail
    - cat3
    - V-38669

# Be sure to set root_forward_email so that this task is executed. See the
# documentation for more details.
- name: V-38446 - Mail system must forward root's email
  lineinfile:
    dest: /etc/aliases
    regexp: "^root"
    line: "root: {{ root_forward_email }}"
  when: root_forward_email is defined
  notify:
    - rehash aliases
  tags:
    - mail
    - cat2
    - V-38446
