---
# Copyright 2015, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

# Restarting services ########################################################
- name: restart auditd
  service:
    name: auditd
    state: restarted

- name: restart chrony
  service:
    name: chrony
    state: restarted

- name: restart fail2ban
  service:
    name: fail2ban
    state: restarted

- name: restart postfix
  service:
    name: postfix
    state: restarted

- name: restart rsyslog
  service:
    name: rsyslog
    state: restarted

- name: restart samba
  service:
    name: smbd
    state: restarted

- name: restart ssh
  service:
    name: ssh
    state: restarted

- name: restart vsftpd
  service:
    name: vsftpd
    state: restarted

# Miscellaneous ##############################################################
- name: generate auditd rules
  command: augenrules --load

- name: rehash aliases
  command: newaliases
