---

  - name: 3.7 (1/3) Install rfkill
    apt:
      name: rfkill
      state: present
    when: disable_wifi
    tags:
      - section3
      - section3.7
      - lvl.1.server
      - lvl.2.workstation
      - not.scored

  - name: 3.7 (2/3) Ensure rfkill kernel module is loaded
    command: modprobe -v rfkill
    register: rfkill
    changed_when: rfkill.stdout != ""
    when: disable_wifi
    tags:
    - section3
    - section3.7
    - lvl.1.server
    - lvl.2.workstation
    - not.scored
      
  - name: 3.7 (3/3) Ensure wireless interfaces are disabled (Not Scored)
    command: rfkill block wifi
    when: disable_wifi
    changed_when: wifi.stdout != '' 
    register: wifi
    tags:
      - section3
      - section3.7
      - lvl.1.server
      - lvl.2.workstation
      - not.scored
      
