---

  - name: 5.3.1 Ensure password creation requirements are configured (Scored)
    apt:
      name: libpam-pwquality
      state: present
    tags:
      - section5
      - section5.3
      - section5.3.1
      - lvl.1.server
      - lvl.1.workstation
      
  - name: 5.3.1 Ensure password creation requirements are configured (Scored)
    lineinfile:
      name: /etc/security/pwquality.conf
      regexp: '^{{item.name}}'
      line: '{{item.name}}={{item.value}}'
    with_items:
      - { name: 'minlen' , value: '14' }
      - { name: 'dcredit' , value: '-1' }
      - { name: 'ucredit' , value: '-1' }
      - { name: 'ocredit' , value: '-1' }
      - { name: 'lcredit' , value: '-1' }
    tags:
      - section5
      - section5.3
      - section5.3.1
      - lvl.1.server
      - lvl.1.workstation
      
  - name: 5.3.1 Ensure password creation requirements are configured (Scored)
    lineinfile:
      name: /etc/pam.d/common-password
      regexp: 'pam_pwquality.so'
      line: 'password        requisite                       pam_pwquality.so try_first_pass retry=3'
    tags:
      - section5
      - section5.3
      - section5.3.1
      - lvl.1.server
      - lvl.1.workstation
      
  - name: 5.3.2 Ensure lockout for failed password attempts is configured (Not Scored)
    lineinfile:
      name: /etc/pam.d/common-auth
      regexp: 'pam_tally2'
      line: 'auth required pam_tally2.so onerr=fail audit silent deny=5 unlock_time=900'
    when: ansible_distribution != 'Debian'      # Need to figure out why this module is breaking login on Debian
    tags:
      - section5
      - section5.3
      - section5.3.2
      - lvl.1.server
      - lvl.1.workstation
      - not.scored
      
  - name: 5.3.3 Ensure password reuse is limited (Scored)
    lineinfile:
      name: /etc/pam.d/common-password
      regexp: '^password\s*sufficient\s*pam_unix.so.*remember=5.*$'
      line: 'password sufficient pam_unix.so remember=5 try_first_pass'
    tags:
      - section5
      - section5.3
      - section5.3.3
      - lvl.1.server
      - lvl.1.workstation
      
  - name: 5.3.4 Ensure password hashing algorithm is SHA-512 (Scored) 1/2
    command: grep '^\bpassword\b.*\bpam_unix\.so\b.*\bsha512\b\.*$' /etc/pam.d/common-password
    failed_when: false
    changed_when: false
    register: hashCheck
    tags:
      - section5
      - section5.3
      - section5.3.3
      - lvl.1.server
      - lvl.1.workstation


  - name: 5.3.4 Ensure password hashing algorithm is SHA-512 (Scored) 2/2
    lineinfile:
      name: /etc/pam.d/common-password
      regexp: '^\bpassword\b.*\bpam_unix\.so\b.*$'
      line: 'password        [success=1 default=ignore]      pam_unix.so obscure sha512'
    when: hashCheck.rc != 0
    changed_when: hashCheck.rc == 0
    tags:
      - section5
      - section5.3
      - section5.3.4
      - lvl.1.server
      - lvl.1.workstation
      
