---

  - name: 8.3.2 Implement Periodic Execution of File Integrity
    cron:
      backup:   true
      minute:   0
      hour:     5
      day:      '*'
      user:     root
      name: 'Check file Integrity'
      state: present
      job:  '/usr/sbin/aide --check'
    tags:
        - section8
        - section8.3
        - section8.3.2
        - lvl.1.server
        - lvl.1.workstation

  - name: 8.3.3 pam_cracklib install
    apt:
      name: pam_cracklib
      state: present
